# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0002_auto_20161202_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='markeraddress',
            name='street',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(),
        ),
    ]
