# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0003_auto_20161205_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markeraddress',
            name='marker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_platform.Marker'),
        ),
    ]
