# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0006_auto_20161206_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markeraddress',
            name='marker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_marker_address', to='sales_platform.Marker'),
        ),
    ]
