# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0011_merchandise_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
