# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0012_auto_20161223_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='sn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_platform.SocialNetwork'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='markeraddress',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='markeraddress',
            name='country',
            field=models.TextField(default='Singapore'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='name',
            field=models.TextField(default='Item'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='merch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_platform.Merchandise'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.TextField(default='Singapore', max_length=60),
        ),
    ]
