# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0013_auto_20161223_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_network', models.IntegerField(choices=[(0, 'Visa'), (1, 'MasterCard'), (2, 'American Express'), (3, 'Discover')], default=0)),
                ('card_number', models.BigIntegerField(null=True)),
                ('cvv_code', models.PositiveSmallIntegerField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_credit_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CreditCards',
            },
        ),
    ]
