# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0015_auto_20161226_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
