# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-30 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0016_creditcard_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_transaction_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_transactions_email', models.EmailField(blank=True, max_length=254)),
                ('tax_recipient', models.TextField(default='', max_length=250)),
                ('amount', models.FloatField(default=0)),
                ('amount_recipient', models.FloatField(default=0)),
                ('amount_genesis_tax', models.FloatField(default=0)),
                ('tax_percent', models.FloatField(default=0)),
                ('transaction_status', models.TextField(blank=True)),
                ('pay_key', models.TextField(default='', max_length=250)),
                ('timestamp', models.DateTimeField(null=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PayTransactions',
            },
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
