# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0017_auto_20161230_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytransactions',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
