# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-30 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0018_paytransactions_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytransactions',
            name='payer_transaction_email',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paytransactions',
            name='recipient_transactions_email',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
