# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0022_auto_20170104_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytransactions',
            name='created_date',
        ),
        migrations.AddField(
            model_name='paytransactions',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paytransactions',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paytransactions',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
