# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0023_auto_20170105_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcredential',
            name='payment_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
