# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0025_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='status',
            field=models.IntegerField(choices=[(0, 'awaiting'), (1, 'sent'), (2, 'error')], default=0),
        ),
    ]
