# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 07:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0034_auto_20170111_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='merch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_platform.Merchandise'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 7, 53, 25, 275454, tzinfo=utc)),
        ),
    ]
