# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0036_auto_20170112_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 14, 30, 29, 798481, tzinfo=utc)),
        ),
    ]
