# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0037_auto_20170116_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='rating_count_votes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 14, 50, 29, 407821, tzinfo=utc)),
        ),
    ]
