# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0040_auto_20170125_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='preview_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='photo/order_items', verbose_name='orderitem_photo'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 25, 12, 54, 29, 532455, tzinfo=utc)),
        ),
    ]
