# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0041_auto_20170125_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_profile_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='photo/merchandise/feedback/user_profile_photo', verbose_name='feedbacks_user_photo'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 26, 14, 43, 53, 757278, tzinfo=utc)),
        ),
    ]
