# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales_platform', '0044_auto_20170213_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 15, 45, 2, 812776, tzinfo=utc)),
        ),
    ]
